gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown

redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
